### ISSUE TITLE
Picking up a package from the ground with a different package in your inventory duplicates the inventory one and deletes the entity one

### ISSUE THREAD

**Issue by anna-s-h** [quat1024/packages#14]
That's the only situation I've found with this problem; transferring between inventories is always safe

**Comment by quat1024** [comment]
Why would that happen they have different nbtttttttt.,,,,,,, What

**Comment by anna-s-h** [comment]
Have you been able to reproduce this issue? I am using Quilt 17.4

**Comment by quat1024** [comment]
Can't reproduce with fabric 0.14.8, api 0.58.0+1.18.2.

Can I get a complete modlist?

**Comment by anna-s-h** [comment]
Sorry, your mod was not at fault with this issue, it just made it noticeable in survival
By testing with chests in creative mode, I found that this mod https://www.curseforge.com/minecraft/mc-mods/upgraded-shulkers causes all non-shulkers to behave in this buggy way. I will report it there and replace it with https://www.curseforge.com/minecraft/mc-mods/reinforced-shulker-boxes

**Comment by quat1024** [comment]
Think i found their bug: https://github.com/kyrptonaught/shulkerupgrades/blob/0ce6cf09c825b6ba9bdf0d57760dc1bb4c7860d2/src/main/java/net/kyrptonaught/upgradedshulker/mixin/ItemEntityMixin.java#L72-L84

I think the intention is to partially fill the player's inventory with the picked-up itemstack before allowing the mod's hopper-box feature to absorb the rest, but line 76 assumes that all pairs of itemstacks that have the same item actually *can* stack with each other, so this symptom happens. (Not really sure why this logic exists at all because vanilla item-pickup logic will do the "insert as many items as possible" stuff already) 

The mistaken code gets called pretty much any time anyone picks up anything, see https://github.com/kyrptonaught/shulkerupgrades/blob/0ce6cf09c825b6ba9bdf0d57760dc1bb4c7860d2/src/main/java/net/kyrptonaught/upgradedshulker/mixin/ItemEntityMixin.java#L45-L52
