### ISSUE TITLE
Clean up Package info (hide Package block composition)

### ISSUE THREAD

**Issue by Eldog02** [quat1024/packages#17]
When I am using a package in my inventory, the first and foremost thing I want to know is what's in the package, not what it's made of. Yet, this information takes up 3/4 of the entire tooltip, which in my opinion is really unbalanced looking! The package's block composition in the tooltip is pretty visually distracting-- There are different colors and font styles that naturally draw the eye more than the essential information.

![Screenshot_1](https://user-images.githubusercontent.com/34759177/198539210-e419a0fb-a892-4cf4-87c0-912cc6349bb8.png)

You can already visually see what the package is made out of; If the user needs to know the exact blocks the package is comprised of in some scenario, I think that information should be relegated to expanding the tooltip (like holding shift while hovering) or enabling debug tooltips.

![Screenshot_2](https://user-images.githubusercontent.com/34759177/198539212-90c3581a-8059-4995-bab5-90b3ba6806ce.png)[^tiny_nitpick]
[^tiny_nitpick]:
    Tiny nitpick: I'd like to see the colors more unified in the tooltip as well. It would be nice if parentheses were the same color as the "layer" of package described (lightest grey text encased in lightest grey parentheses, etc). I think it would make more sense if the "Ultimately contains" line was also the same color as the innermost layer instead of always the darkest grey. Maybe it would be a cute touch if the number's color was the same as the package's front color?

**Comment by quat1024** [comment]
Sure I guess I can throw this on shift, just thought the tooltip looked a bit plain lol. Yes, it's important to surface this information because the point of Packages is that they *stack*, being able to tell exactly which blocks were used so you can produce more that will 100% for-sure stack with your existing ones is important

"Ultimately contains" was a hasty addition, I didn't want it to draw too much attention which is why I chose a darker color.

The parenthesis coloration is fine, it's `Package ( <thing inside the package> )`, parens are at the top level.
