### ISSUE TITLE
(Forge 1.18.2/3.1) Weird Display Item Lighting on Create Contraptions 

### ISSUE THREAD

**Issue by Bobisnotap** [quat1024/packages#18]
The display items of packages on create contraptions appear to ignore skylight, but are affected by block light on contraptions.
![image](https://user-images.githubusercontent.com/60948714/198733829-54404cd8-32af-421b-b10d-deb3def18184.png)
![image](https://user-images.githubusercontent.com/60948714/198733839-3f12a2f7-f094-4242-957f-471e4d9e67ad.png)
No fancy render changing mod being used, might be worth testing on other versions/loaders.

**Comment by quat1024** [comment]
I'm astonished they work at all.

Like, no seriously - this could just as easily be a bug like "packages are invisible on create contraptions", or "packages render with my fallback pink-and-black terracotta model i use when i can't determine the model", or "packages on Create contraptions crash the game"

The bug being about something as banal as lighting? Serious props to the Create team

**Comment by quat1024** [comment]
I intentionally query `LevelRenderer#getLightColor` myself instead of trusting the `light` parameter because the blocks are opaque. Without this line you always get black items even outside of a contraption.

https://github.com/quat1024/packages/blob/78c91c4d21ebcf62f6cbfe4453abd419c8f4d149/Xplat/src/main/java/agency/highlysuspect/packages/client/PackageRenderer.java#L49-L50

What's really surprising to me is that it works with block light but not sky light, because I don't treat them differently - getLightColor returns combined light. If Create has a custom implementation of this method it might be broken; if it doesn't, maybe this method is just bugged when calling it from whatever context Create is rendering things in and always returns zero skylight.

I don't know anything about how contraption rendering works, btw, Flywheel is insanely complicated.
