### ISSUE TITLE
Package Rendering gets real weird when you introduce Canvas 

### ISSUE THREAD

**Issue by Bluberry-Kat** [quat1024/packages#3]
minecraft 1.16.4, fabric api 0.25.1, Canvas 1.0.989, Packages 1.1 
I'll let the screenshots speak for themselves, was reproduced in a lightweight instance with only the relevant mods 
![2020-11-07_19 51 19](https://user-images.githubusercontent.com/20749209/98454484-e3de2500-2132-11eb-94cf-8c8d99faa164.png)
![2020-11-07_19 51 47](https://user-images.githubusercontent.com/20749209/98454486-e8a2d900-2132-11eb-85b7-74693b6a13e7.png)

**Comment by quat1024** [comment]
in my dev environment it seems to crash whenever i look at a package or press shift around one, so, that's also pretty cool

ed: only happens when canvas's Experimental Rendering Pipeline is turned on, and the thing at fault is the text rendering

**Comment by quat1024** [comment]
looking into why this happens and i... have no idea!
pretty sure it's something with `FakeSprite` being cursed, which is fair because it's cursed
i've asked around on grondag's discord, hopefully someone can figure it out

as a goofy temporary workaround, you can change `assets/packages/models/block/package.json` (original [here](https://raw.githubusercontent.com/quat1024/packages/trunk/src/main/resources/assets/packages/models/block/package.json)) with a resource pack and replace `packages:special/frame` and `packages:special/inner` with references to whatever other textures you want

this effectively disables the dynamic retexturing stuff, at the cost of... the dynamic retexturing stuff being disabled, so all packages look the same (but at least they won't look broken)

**Comment by quat1024** [comment]
futzed with it a bit, with some hacky Canvas-specific workarounds it- well, at least it uses the *right* texture? i have no idea how i managed to bend it into an L
![image](https://user-images.githubusercontent.com/2068021/98459158-0e95a100-2166-11eb-8153-1cad1ded8166.png)

compare no canvas
![image](https://user-images.githubusercontent.com/2068021/98459191-51577900-2166-11eb-84f4-7d008ac7eda3.png)
